# See LICENSE file for full copyright and licensing details.

{
    'name': 'Whatsapp Livechat',
    'version': '15.0.0.1.0',
    'license': 'OPL-1',
    'author': "Alphasoft",
    'sequence': 1,
    'website': 'https://www.alphasoft.co.id/',
    'images':  ['images/main_screenshot.png'],
    'summary': 'This module is used for Whatsapp to Livechat',
    'category': 'Extra Tools',
    'depends': [
        'im_livechat', 
        'mail',
        'aos_whatsapp', 
        #'aos_api_rest', 
        #'aos_whatsapp_bot', 
    ],
    'data': [
        'data/whatsapp_data.xml',
        'views/mail_message.xml',
        #'views/res_partner.xml',
        #'views/api_rest_path.xml',
        #'wizard/whatsapp_compose_view.xml',
    ],
    'external_dependencies': {'python': ['html2text']},
    'demo': [],
    'test': [],
    'css': [],
    'js': [],
    'price': 0,
    'currency': 'EUR',
    'installable': True,
    'application': False,
    'auto_install': False,
}
